### PR TITLE
Propose solutions to solve installation on ubuntu linux 64bits

### PR DESCRIPTION
**Pull request by jmespadero**
Propose solutions to solve installation on ubuntu linux 64bits

### CODE REVIEW

**Comment by jmespadero** [comment]
Please, consider the inclusion of this note to help install on linux. My linux version is ubuntu LTS 14-04

**Comment by dfelinto** [comment]
Hi did you intentionally closed this pull request?

**Comment by PyrApple** [comment]
NO, definitely not (I may have accidentally through 'git commit'??)

David

**Comment by PyrApple** [comment]
is there a way to recall it or shall I apply the patch proposed in 
https://github.com/BlenderVR/manual/pull/1.patch
(I mean, that would be more classy if we actually accepted the pull request rather than manually doing our own, 
I'll try to learn more about this Jose)

**Comment by dfelinto** [comment]
@PyrApple I just reopened. My question was more related to whether this is still to be considered for inclusion or not (to apply you only need to click on Merge pull request in the site)

**Comment by jmespadero** [comment]
No. I think that I closed by error. The changes I proposed to the manual are valid (I needed to correctly install blenderVR with the new instructions)

The problem with ensurepip is a know issue in ubuntu, and also for linuxmint.

**Comment by dfelinto** [comment]
Thanks, pushed then :)

**Pull request merged**
